services:
  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    volumes:
      - ./backend:/var/www/html/
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "9000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./docker/front
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - db
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"           
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 1806
      MYSQL_DATABASE: ejeapi
      MYSQL_USER: paula
      MYSQL_PASSWORD: 1806
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/incidents.sql:/docker-entrypoint-initdb.d/incidents.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
