version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/var/www/html/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gdi
      MYSQL_USER: paula
      MYSQL_PASSWORD: 1806
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/incidents.sql:/docker-entrypoint-initdb.d/incidents.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge