version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/html/
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes_from:
      - db_data

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend:/var/www/html/
      - /app/node_modules
    depends_on:
      - dbdata
    ports:
      - "3000:3000"
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1806
      MYSQL_DATABASE: gdi
      MYSQL_USER: paula
      MYSQL_PASSWORD: 1806
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/incidents.sql:/docker-entrypoint-initdb.d/incidents.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge