services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/back/Dockerfile
    volumes:
      - ./back:/var/www/html/
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "9000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./docker/front
      dockerfile: ../docker/front/Dockerfile
    volumes:
      - ./frontend:/var/www/html/
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"           
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend


  db:
    image: mysql
    environment:
      MYSQL_PORT: 1806
      MYSQL_DATABASE: gdi
      MYSQL_USER: paula
      MYSQL_PASSWORD: 1806
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/incidents.sql:/docker-entrypoint-initdb.d/incidents.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge